# Generated by Django 2.1.2 on 2018-11-22 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mantencion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodManten', models.CharField(max_length=30)),
                ('FechaMante', models.DateField()),
                ('CodBici', models.CharField(max_length=30)),
                ('Descripcion', models.CharField(max_length=300)),
            ],
        ),
    ]
