# Generated by Django 2.1.2 on 2018-11-24 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181124_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TarjetaPrepa', models.CharField(max_length=30)),
            ],
        ),
    ]
